# Generated by Django 5.0.6 on 2024-06-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0002_aboutpagesubheadingsdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagedetails',
            name='details_content',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='aboutpagedetails',
            name='details_heading',
            field=models.CharField(max_length=250),
        ),
    ]
