# Generated by Django 5.0.6 on 2024-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0003_alter_aboutpagedetails_details_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagedetails',
            name='details_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpagedetails',
            name='details_heading',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpagesubheadingsdetails',
            name='details_subHeading',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpagesubheadingsdetails',
            name='details_subHeadingContent',
            field=models.TextField(),
        ),
    ]
