# Generated by Django 5.0.6 on 2024-06-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0004_alter_aboutpagedetails_details_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagesubheadingsdetails',
            name='details_subHeading',
            field=models.CharField(max_length=200),
        ),
    ]
