# Generated by Django 5.0.6 on 2024-06-16 07:36

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.FileField(default=None, max_length=250, null=True, upload_to='blogs/')),
                ('blog_heading', models.CharField(max_length=200)),
                ('blog_paragraph', tinymce.models.HTMLField()),
            ],
        ),
    ]
