# Generated by Django 5.0.6 on 2024-06-16 07:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_heading', unique=True),
        ),
    ]
