# Generated by Django 5.0.6 on 2024-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactUsAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactUsEmail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactUsPhone', models.CharField(max_length=100)),
            ],
        ),
    ]
