# Generated by Django 5.0.6 on 2024-06-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseImage', models.FileField(default=None, max_length=250, null=True, upload_to='courses/')),
                ('courseUpdateDate', models.DateField(auto_now=True)),
                ('courseName', models.CharField(max_length=50)),
                ('coursePrice', models.CharField(max_length=50)),
            ],
        ),
    ]
