# Generated by Django 5.0.6 on 2024-06-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courselastdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselastdate',
            name='courseLastDate',
            field=models.DateTimeField(),
        ),
    ]
