# Generated by Django 5.0.6 on 2024-06-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courselastdate_courselastdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseIncludeIcon', models.FileField(default=None, max_length=250, null=True, upload_to='courses/')),
                ('courseIncludecontent', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='courseIncludes',
            field=models.ManyToManyField(to='courses.courseinclude'),
        ),
    ]
