# Generated by Django 5.0.6 on 2024-06-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnContent', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='courseLearns',
            field=models.ManyToManyField(to='courses.courselearn'),
        ),
    ]
