# Generated by Django 5.0.6 on 2024-06-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_courses_courseincludes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinclude',
            name='courseIncludeIcon',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='courseinclude',
            name='courseIncludecontent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courselearn',
            name='learnContent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='CourseOverView',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseDesc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseInstructor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseInstructorJob',
            field=models.CharField(max_length=200),
        ),
    ]
