# Generated by Django 5.0.6 on 2024-06-16 15:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courseinclude_courseincludeicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='CourseOverView',
            field=tinymce.models.HTMLField(),
        ),
    ]
